apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: eix6fgn7z-python 
  janus-idp.io/tekton: eix6fgn7z-python
  backstage.io/kubernetes-id: eix6fgn7z-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eix6fgn7z-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml